{% set GIT_TAG_CLEAN = environ.get('GIT_TAG_CLEAN', '0.0.0') %}
{% set GIT_TAG_REF = environ.get('GIT_TAG_REF', 'main') %}
{% set deps = [
    "pytest"
] %}

package:
  name: openghg_defs
  version: "{{ GIT_TAG_CLEAN }}"

source:
  git_url: https://github.com/openghg/openghg_defs.git
  git_rev: "{{ GIT_TAG_REF }}"

build:
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"
  script_env:
    - GIT_TAG_CLEAN
    - GIT_TAG_REF

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - wheel
    - hatchling
    - uv-dynamic-versioning
  run:
    {% for package in deps %}
    - {{ package }}
    {% endfor %}

test:
  imports:
    - openghg_defs

about:
  home: "https://github.com/openghg/openghg_defs"
  license: MIT
  license_family: MIT
  summary: "Supplementary definition data for OpenGHG"
