{% set version = environ.get('PKG_VERSION', '0.0.0').lstrip('v') %}

package:
  name: openghg_defs
  version: "{{ version }}"

source:
  git_url: https://github.com/openghg/openghg_defs.git
  git_rev: {{ version }}

build:
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    {% for package in deps %}
    - {{ package }}
    {% endfor %}

test:
  imports:
    - openghg_defs

about:
  home: "https://github.com/openghg/openghg_defs"
  license: MIT
  license_family: MIT
  summary: "Supplementary definition data for OpenGHG"
