package:
  name: "openghg_defs"
  version: 0.0.2

source:
  git_url: https://github.com/openghg/openghg_defs.git
  git_tag: minChanges

build:
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools

test:
  imports:
    - openghg_defs


about:
  home: "https://github.com/openghg/openghg_defs"
  license: MIT
  license_family: MIT
  summary: "OpenGHG supplementary metadata"
  doc_url: https://docs.openghg.org
  dev_url: "https://github.com/openghg/openghg_defs"

extra:
  recipe-maintainers:
    - gareth-j
