{% set version = PKG_VERSION | replace("v", "") %}
{% set deps = ["python >=3.11", "numpy", "pandas"] %}

package:
  name: openghg_defs
  version: "{{ version }}"

source:
  git_url: https://github.com/openghg/openghg_defs.git
  git_depth: 1
  git_rev: "{{ environ.get('PKG_VERSION', 'v0.0.0') }}"  # uses the Git tag to checkout

build:
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"
  script_env:
    GIT_TAG

requirements:
  host:
    - python >=3.11
    - pip
    - hatchling
    - uv
  run:
    {% for package in deps %}
    - {{ package }}
    {% endfor %}

test:
  imports:
    - openghg_defs

about:
  home: "https://github.com/openghg/openghg_defs"
  license: MIT
  license_family: MIT
  summary: "Supplementary definition data for OpenGHG"
