{% set GIT_TAG = environ.get('GIT_TAG', '0.0.0') %}
{% set deps = [
    "pytest"
] %}

package:
  name: openghg_defs
  version: "{{ GIT_TAG }}"

source:
  git_url: https://github.com/openghg/openghg_defs.git
  git_rev: "{{ GIT_TAG }}"

build:
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . -vv"
  script_env:
    GIT_TAG

requirements:
  host:
    - python >=3.11
    - python >=3.11
    - pip
    - hatchling
    - uv
    - hatchling
    - uv
  run:
    {% for package in deps %}
    - {{ package }}
    {% endfor %}

test:
  imports:
    - openghg_defs

about:
  home: "https://github.com/openghg/openghg_defs"
  license: MIT
  license_family: MIT
  summary: "Supplementary definition data for OpenGHG"
